### ISSUE TITLE
Proposal to Add Lighthouse scores to each site

### ISSUE THREAD

**Issue by knaackbuilt** [civichackingagency/scangov-docs#5]
While the metrics used to baseline each of the state and federal websites are good at demonstrating basic web fundamentals, you could dive deeper into this by reporting Lighthouse scores for each site as a metric as well. Lighthouse isn't perfect - especially in terms of accessibility scanning - but it does provide some additional benchmarks for comparison broken down into useful categories. 

Zach Leatherman has a webcomponent for adding lighthouse scores directly to a page or https://www.speedlify.dev/ which can be used to benchmark sites over time with several other metrics included. I'm sure there's other options out there as well, but these are pre-packaged, open source, and provide useful data. 

Alternatively you could roll your own and use the lighthouse cli to run periodic reports and report scores in any number of other ways. 

Would love to discuss further or assist with implementation. Thanks!

**Comment by lukefretwell** [comment]
@knaackbuilt we use this repo for docs. Could you add to the [scangov repo](https://github.com/civichackingagency/scangov/issues/new/choose), and we can discuss where to go from there?

Also, feel free to [join the community](https://docs.scangov.org/community).

Thank you!
